language: c

os:
  - linux
  - osx

dist: focal # 20.04

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
      - dpkg
      - gcc
      - libcunit1-dev
      - libibverbs-dev
      - librdmacm-dev
      - make
      - pkg-config
      - xsltproc

script:
  ci/build.sh
